force-app/main/default/objects/Contact/fields/MessageBirdContactId__c.field-meta.xml
<CustomField>
    <fullName>MessageBirdContactId__c</fullName>
    <externalId>true</externalId>
    <label>MessageBirdContactId</label>
    <length>32</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/MessageBirdConversationId__c.field-meta.xml
<CustomField>
    <fullName>MessageBirdConversationId__c</fullName>
    <externalId>true</externalId>
    <label>MessageBirdConversationId</label>
    <length>32</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/MessageBirdCountryCode__c.field-meta.xml
<CustomField>
    <fullName>MessageBirdCountryCode__c</fullName>
    <label>Message Bird Country Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>MessageBirdCountryCodes</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/MessageBirdDisplayWindowConfiguration__c.field-meta.xml
<CustomField>
    <fullName>MessageBirdDisplayWindowConfiguration__c</fullName>
    <defaultValue>false</defaultValue>
    <label>MessageBirdDisplayWindowConfiguration</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/globalValueSets/MessageBirdCountryCodes.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>USA (+1)</fullName>
        <label>USA</label>
    </customValue>
    <customValue>
        <fullName>MEX (+521)</fullName>
        <label>MEX</label>
    </customValue>
    <customValue>
        <fullName>CAN (+1)</fullName>
        <label>CAN</label>
    </customValue>
    <masterLabel>Message Bird Country Codes</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ChatQuery.cls
public with sharing class ChatQuery {
  public static Contact getContact(String recordId) {
    return [
      SELECT
        Id,
        Phone,
        MobilePhone,
        OtherPhone,
        MessageBirdContactId__c,
        MessageBirdConversationId__c,
        MessageBirdCountryCode__c,
        MessageBirdDisplayWindowConfiguration__c
      FROM Contact
      WHERE Id = :recordId
      WITH SECURITY_ENFORCED
    ];
  }
}